[package]
name = "mattrix"
repository = "https://github.com/AvalancheSnowman/MaTTrix"
keywords = ["MITRE", "MITRE-ATT&CK", "STIX", "terminal", "CLI", "Rust"]
readme = "README:md"
categories = ["command-line-interface"]
description = "CLI en Rust para consultar información de la matriz MITRE-ATT&CK directamente desde la terminal."
license = "MIT"
authors = ["Avalanche Snowman <snowmanflake2@gmail.com>"]
exclude = ["*.log", ".github"]
version = "0.1.0"
edition = "2024"

[dependencies]
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.0", features = ["derive"] }
colored = "3.0"
dirs = "6.0"